origin_z: 0.0
obstacle_range: 15.0 #50
raytrace_range: 15.0 #3

transform_tolerance: 0.5
meter_scoring: true

footprint_padding: 0.0

static_layer:
  map_topic: map_static
  subscribe_to_updates: false
  static_map: true

inflater_layer:
  enabled:              true
  inflation_radius:  0.2 #1.75   #0.4  # 1.75 # max. distance from an obstacle at which costs are incurred for planning
  cost_scaling_factor: 1.0 #2.58 #9.0  # 2.58 # exponential rate at which the obstacle cost drops off (default: 10)
  inflate_unkown: true

obstacle_layer:
  enabled:              true
  combination_method: 1
  observation_sources: scan
  clearing: true
  scan:
    data_type: LaserScan
    topic: robot_pose_LaserScan
    marking: true
    clearing: true
    inf_is_valid: true
    min_obstacle_height: 0.0
    max_obstacle_height: 2.0
    obstacle_range: 15.0
    raytrace_range: 15.0

# recovery_behaviors:
#   - name: 'clear_costmap'
#     type: 'clear_costmap_recovery/ClearCostmapRecovery'

# clear_costmap:
#   reset_distance: 0.0
#   force_updating: true
#   affected_maps: global_costmap
#   layer_names: [obstacle_layer, inflater_layer]
