global_costmap:
  global_frame: map
  robot_base_frame: floating_frame #human1/base_footprint 
  update_frequency: 10
  publish_frequency: 10
  robot_radius: 0.3
  clearing: true
  # always_send_full_costmap: true #this is to have every update on /costmap topic to be read by socialspace.cpp

  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
  #layer for updating position of agents
  #uncomment to add agents on costmap and run the agents_tracker.py in laucnh file _locate_pub.launch
  # - {name: any_name, type: "agents_layer::AgentsLayer"}

  inflater_layer:
    inflation_radius: .2 #0.6
    cost_scaling_factor: 1.0 #9.0